import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu/Menu";
import Preloader from "@/components/preloader/Preloader";
import { MuseoModerno } from "next/font/google";
import localFont from 'next/font/local'
// const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({
  src: '../../public/fonts/Satoshi-Medium.woff2',
  display: 'swap',
  // weight: ["400", "500", "600", "700", "800", "900"],

})
const museo = MuseoModerno({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Jay",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={myFont.className}>
        <Preloader/>
      
        <Menu/>
        {children}</body>
    </html>
  );
}
























// "use client"; // Add this line at the top of the file

// import { useEffect, useState } from "react";
// import Menu from "@/components/menu/Menu";
// import Preloader from "@/components/preloader/Preloader";
// import { MuseoModerno } from "next/font/google";
// import './globals.css'

// const museo = MuseoModerno({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900"],
// });

// export default function RootLayout({ children }) {

//   const [loading, setLoading] = useState(true);

//   useEffect(() => {
//     // Simulate a delay to show preloader for demo purposes
//    setTimeout(() => setLoading(false), 5000);
//   }, []);

//   return (
//     <html lang="en">
//       <body className={museo.className}>
//         {loading && <Preloader />}
//         <Menu />
//         {children}
//       </body>
//     </html>
//   );
// }




